version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: America/Puerto_Rico
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
    commit-message:
      prefix: security
